name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v1

      - name: Run linters - ruff check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./"