name: CI PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      RUFF_PROJECT_VERSION: "0.15.15"
      VALUE: ${{ secrets.SECRET }}
    steps:
      - name: Actions checkout
        uses: actions/checkout@v1

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: ${{ env.RUFF_PROJECT_VERSION }}

      - name: Echo secret
        run: echo ${{ env.VALUE }}

      - name: Run check syntax
        run: ruff check --fix
      
      - name: Run check format
        run: ruff format --check
