name: CI PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Actions checkout
        uses: actions/checkout@v1

      - name: Run linters - ruff check
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format